services:
  mml-db:
    image: postgres:15
    container_name: mml-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: mml_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend-mobile:
    build:
      context: ./frontend
      target: mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - mobile
    tty: true
    stdin_open: true

  frontend-web:
    build:
      context: ./frontend
      target: web
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - web

  backend:
    build: ./backend
    container_name: mml-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://postgres:your_password_here@mml-db:5432/mml_db
    depends_on:
      - mml-db

volumes:
  pgdata: